version: '3.9'
services:
  postgresql:
    container_name: postgresql-tcc
    environment:
      POSTGRES_USER: tcc
      POSTGRES_PASSWORD: tcc20202023
      POSTGRES_DB: tcc
    image: postgres:15-alpine3.17
    ports:
      - "5432:5432"
    networks:
      - tcc
    volumes:
      - ./postgresql/scripts:/docker-entrypoint-initdb.d
    restart: always

networks:
  tcc:
    driver: bridge